### ISSUE TITLE
Requirements versions

### ISSUE THREAD

**Issue by mitramir55** [saturnMars/derivingStructuredInsightsFromSustainabilityReportsViaLargeLanguageModels#2]
Hi,

I've been trying to implement your code and I noticed there are a few errors regarding package versions. 

For example, `code/end2end_KG/genSRL/end2end_srl.py` only works with kor==1.0.0
```

    chain.prompt.format_prompt(text="[user input]").to_string(), 
    ^^^^^^^^^^^^
AttributeError: 'RunnableSequence' object has no attribute 'prompt'

```
I think you should upgrade the chain creation as the previous one is deprecated. Or add the versions to requirements.txt.
`chain = create_extraction_chain(llm_model, schema, encoder_or_encoder_class='json') #, instruction_template=prompt_template) 
`
or add the versions to requirements.txt as well.

Thanks.
